In [3]:
#텐서 생성 및 변환
import torch
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]], device="cuda:0")) #gpu에 텐서 생성
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64)) #dtype 이용해 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [5]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy()) #텐서 ndarray로 변경

temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.to("cpu").numpy()) # gpu상의 텐서를 cpu의 텐서로 변환후 ndarray로 변환

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [6]:
#텐서 인덱스 조작
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0],temp[1],temp[-1]) #인덱스 접근``
print(temp[2:5], temp[4:-1]) #슬라이싱

tensor(1.) tensor(2.) tensor(7.)
tensor([3., 4., 5.]) tensor([5., 6.])


In [7]:
#텐서 연산
#텐서간 타입이 다르면 연산이 불가능하니 주의하자

v = torch.tensor([1,2,3])
w = torch.tensor([3,4,5])
print(v-w)

tensor([-2, -2, -2])


In [6]:
#텐서 차원조작
temp = torch.tensor([[1,2],[3,4]])

print(temp.shape)
print(temp.view(4,1)) # 4x1 행렬로 변경
print(temp.view(-1))  # 1차원 벡터로 변경
print(temp.view(4,-1)) # 자동으로 행에 맞는 열로 변경
print(temp.view(-1,1)) # 자동으로 열에 맞는 행으로 변경

torch.Size([2, 2])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])
